### ISSUE TITLE
setup.py issue on python 3.11

### ISSUE THREAD

**Issue by biemster** [Dadoum/pyprovision#1]
following the setup instructions does not seem to work on python 3.11:
```
✘-1 ~/temp/pyprovision [main|✔] 
22:31 $ python -m pip install . --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Processing /home/lars/temp/pyprovision
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/lars/temp/pyprovision/setup.py", line 46, in <module>
          ext_modules=[DubExtension('pyprovision', ["pyprovision"])],
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: DubExtension.__init__() takes 2 positional arguments but 3 were given
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```
There's an easy fix for this, remove ` ["pyprovision"]` from
```

        File "/home/lars/temp/pyprovision/setup.py", line 46, in <module>
          ext_modules=[DubExtension('pyprovision', ["pyprovision"])],
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: DubExtension.__init__() takes 2 positional arguments but 3 were given
```

**Comment by Dadoum** [comment]
Oh, I think I forgot to stage my changes to it in one of the lasts commit. Oops

**Comment by biemster** [comment]
Oops!

**Comment by Dadoum** [comment]
Fixed
